services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-container
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1;' $MYSQL_DATABASE"]
      interval: 5s
      timeout: 5s
      retries: 5
  fastapi:
    build:
      context: .
    container_name: fastapi-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
