version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data: