version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: portfolio
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
